#!/bin/sh

DIR="$HOME/storage/shared/.trash"
LOC="$DIR/trash.tar"

if [ $# -eq 0 ]; then
	echo "Which file you decided to trash?"
	exit 1
fi

if [ -e "$LOC" ]; then
	echo "trash appended $@"
	tar -rf "$LOC" "$@"
else 
	echo "trash created $@"
	mkdir -p "$DIR"
	tar -cf "$LOC" "$@"
fi

echo "trash done"
